language: python
cache:
    directories:
        "$HOME/.cache/pip"
python: 3.5
sudo: false
addons:
    apt:
        packages:
            libzookeeper-mt-dev
env:
    - TOX_ENV=py27
    - TOX_ENV=py35
install:
    - pip install -U pip
    - pip install tox
script:
    - tox -e $TOX_ENV
